### ISSUE TITLE
Incompatible versions of Kotlin metadata - 1.5.1 expected

### ISSUE THREAD

**Issue by ikurek** [usefulness/easylauncher-gradle-plugin#324]
I've added the `easylauncher` dependency in version `5.1.1` and Gradle sync returns following error:

```
com.project.starter/easylauncher/5.1.1/aa3307d8bfca4f9f3cb222f52c82095333094081/easylauncher-5.1.1.jar!/META-INF/easylauncher.kotlin_module: 
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```

I'm using the `build-logic` pattern for Gradle, and my convention plugin for `easylauncher` is pretty straightforward:

```kotlin
class EasylauncherConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) = with(target) {
        pluginManager.apply("com.starter.easylauncher")
    }
}
```

I've checked the dependency graph of my project with `./gradlew dependencies` but none of the deps I have include Kotlin versions below `1.6.20`. The complete list of other dependencies I've included:
```toml
[versions]
androidDesugarJdkLibs = "1.1.5"
androidGradlePlugin = "7.2.1"
androidxAppCompat = "1.4.2"
androidxCore = "1.8.0"
detekt = "1.20.0"
easylauncherGradlePlugin = "5.1.1"
junit4 = "4.13.2"
kotlin = "1.7.0"
kotlinterGradlePlugin = "3.10.0"
material3 = "1.6.1"

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
easylauncher-gradlePlugin = { group = "com.project.starter", name = "easylauncher", version.ref = "easylauncherGradlePlugin" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradlePlugin = { group = "org.jmailen.gradle", name = "kotlinter-gradle", version.ref = "kotlinterGradlePlugin" }
material3 = { group = "com.google.android.material", name = "material", version.ref = "material3" }
```

I did some investigating but I failed to understand where the issue may come from. It is caused by adding the `easylauncher` plugin, because removing the plugin dependency fixes Gradle sync problems, but I'm not able to locate it's source. Any advice on how to approach this?
